export const REQUEST_TIME_ENTRIES = 'REQUEST_TIME_ENTRIES';
export const REQUEST_TIME_ENTRIES_SUCCESS = 'REQUEST_TIME_ENTRIES_SUCCESS';
export const REQUEST_TIME_ENTRIES_FAILURE = 'RETRIEVE_TIME_ENTRIES_FAILURE';
