export const FETCH_TIME_ENTRIES_REQUEST = 'FETCH_TIME_ENTRIES_REQUEST';
export const FETCH_TIME_ENTRIES_REQUEST_SUCCESS =
  'FETCH_TIME_ENTRIES_REQUEST_SUCCESS';
export const FETCH_TIME_ENTRIES_REQUEST_FAILURE =
  'FETCH_TIME_ENTRIES_REQUEST_FAILURE';

export const DELETE_TIME_ENTRY_REQUEST = 'DELETE_TIME_ENTRY_REQUEST';
export const DELETE_TIME_ENTRY_REQUEST_SUCCESS =
  'DELETE_TIME_ENTRY_REQUEST_SUCCESS';
export const DELETE_TIME_ENTRY_REQUEST_FAILURE =
  'DELETE_TIME_ENTRY_REQUEST_FAILURE';

export const ADD_TIME_ENTRY_REQUEST = 'ADD_TIME_ENTRY_REQUEST';
export const ADD_TIME_ENTRY_REQUEST_SUCCESS = 'ADD_TIME_ENTRY_REQUEST_SUCCESS';
export const ADD_TIME_ENTRY_REQUEST_FAILURE = 'ADD_TIME_ENTRY_REQUEST_FAILURE';
