export const ADD_TIME_ENTRY_FAILURE = 'ADD_TIME_ENTRY_FAILURE';
export const ADD_TIME_ENTRY_REQUEST = 'ADD_TIME_ENTRY_REQUEST';
export const ADD_TIME_ENTRY_SUCCESS = 'ADD_TIME_ENTRY_SUCCESS';

export const DELETE_TIME_ENTRY_FAILURE = 'DELETE_TIME_ENTRY_FAILURE';
export const DELETE_TIME_ENTRY_REQUEST = 'DELETE_TIME_ENTRY_REQUEST';
export const DELETE_TIME_ENTRY_SUCCESS = 'DELETE_TIME_ENTRY_SUCCESS';

export const FETCH_TIME_ENTRIES_FAILURE = 'FETCH_TIME_ENTRIES_FAILURE';
export const FETCH_TIME_ENTRIES_REQUEST = 'FETCH_TIME_ENTRIES_REQUEST';
export const FETCH_TIME_ENTRIES_SUCCESS = 'FETCH_TIME_ENTRIES_SUCCESS';

export const FILTER_TIME_ENTRIES_BY_CLIENT = 'FILTER_TIME_ENTRIES_BY_CLIENT';
